### PR TITLE
Adding options

### PR DESCRIPTION
**Pull request by brycereynolds**

### CODE REVIEW

**Comment by jamesplease** [comment]
What's the use case for `options`?

**Comment by brycereynolds** [comment]
I think the benefit is in components with a fair amount of nesting. It's nice not having every component along the way have to understand what to pass when a user has supplied props used for configuration. An example can be seen when looking at the cpe-react-file-system component. If I supply a prop like `allowSelect` and only the lowest level components care about that, it either gets explicitly passed along (and subsequently updated when changed) or it's passed using something like `...this.props` (or something slightly more specific).

Passing an explicit options /settings param in addition to the htr may help clean that up.

**Comment by jamesplease** [comment]
Makes sense! :v: Thanks for elaborating @brycereynolds 🙂

**Comment by tbranyen** [comment]
Hey @brycereynolds sorry I didn't respond to this for so long. Part of me was anxious about adding more props into this module (since its called hooks theme refs). I'm thinking we may be able to do something else to accommodate this and future use cases without having to bikeshed over which props are deemed important enough.

What do you think of the following proposal?

``` js
import React, { Component } from 'react';
import htr from 'hooks-theme-refs';

// `htr.props` would be a `new Set()` for uniqueness and would be global.
htr.props.add('options');

class MyComponent extends Component {
  render() {
    // Pass an array as a second argument to the htr function would augment
    // the props deep merged only in this local case.
    const { options } = htr(this.props, ['options']);
  }
}
```

**Comment by tbranyen** [comment]
Reference PR here: https://github.com/tbranyen/hooks-theme-refs/pull/4

**Comment by tbranyen** [comment]
Released in 1.0.0. Lets keep this open since we can decide if we want to also white-list options by default.

**Comment by tbranyen** [comment]
Going to close this due to inactivity, feel free to re-open if we should reconsider adding options as a core default.

**Pull request closed without merging**
